import type { ProductWithImages } from "@/lib/supabase/types";

/**
 * Demo catalog used only when Supabase is not yet configured, so the storefront
 * renders during development. Replaced by real data once the project is live.
 * Images are placeholders (picsum) until real photos are uploaded.
 */
function img(seed: string) {
  return `https://picsum.photos/seed/${seed}/800/1000`;
}

function make(
  p: Omit<ProductWithImages, "product_images" | "measurements" | "published" | "updated_at"> & {
    images: string[];
  }
): ProductWithImages {
  const { images, ...rest } = p;
  return {
    ...rest,
    measurements: {},
    published: true,
    updated_at: rest.created_at,
    product_images: images.map((storage_path, i) => ({
      id: `${rest.id}-img-${i}`,
      product_id: rest.id,
      storage_path,
      alt: rest.title,
      position: i,
    })),
  };
}

export const SAMPLE_PRODUCTS: ProductWithImages[] = [
  make({
    id: "s1",
    slug: "blamont-silkikjoll",
    title: "Síðerma silkikjóll",
    description: "Glæsilegur silkikjóll í djúpfjólubláum tón. Fullkominn í veisluna.",
    brand: "Ganni",
    gender: "women",
    category: "dresses",
    size: "M",
    color: "Fjólublár",
    condition: "excellent",
    price_isk: 12900,
    original_price_isk: 38900,
    status: "available",
    created_at: "2026-06-20T10:00:00Z",
    images: [img("remoda-dress1a"), img("remoda-dress1b")],
  }),
  make({
    id: "s2",
    slug: "ullarkapa-camel",
    title: "Ullarkápa í kamellit",
    description: "Klassísk ullarkápa, hlý og tímalaus. Lítið notuð.",
    brand: "Max Mara",
    gender: "women",
    category: "outerwear",
    size: "38",
    color: "Kamel",
    condition: "excellent",
    price_isk: 24900,
    original_price_isk: 89000,
    status: "available",
    created_at: "2026-06-22T10:00:00Z",
    images: [img("remoda-coat2a"), img("remoda-coat2b")],
  }),
  make({
    id: "s3",
    slug: "denim-jakki-vintage",
    title: "Vintage gallajakki",
    description: "Original vintage gallajakki með fínu sliti. Unisex snið.",
    brand: "Levi's",
    gender: "unisex",
    category: "outerwear",
    size: "L",
    color: "Blár",
    condition: "good",
    price_isk: 8900,
    original_price_isk: null,
    status: "available",
    created_at: "2026-06-25T10:00:00Z",
    images: [img("remoda-denim3a")],
  }),
  make({
    id: "s4",
    slug: "kasmir-peysa-graa",
    title: "Kasmírpeysa, grá",
    description: "Mjúk 100% kasmírpeysa. Eins og ný.",
    brand: "COS",
    gender: "women",
    category: "knitwear",
    size: "S",
    color: "Grá",
    condition: "new_with_tags",
    price_isk: 9900,
    original_price_isk: 21900,
    status: "available",
    created_at: "2026-06-26T10:00:00Z",
    images: [img("remoda-knit4a"), img("remoda-knit4b")],
  }),
  make({
    id: "s5",
    slug: "herraskyrta-oxford",
    title: "Oxford herraskyrta",
    description: "Klassísk ljósblá oxford skyrta. Vel með farin.",
    brand: "Ralph Lauren",
    gender: "men",
    category: "tops",
    size: "M",
    color: "Ljósblár",
    condition: "good",
    price_isk: 5900,
    original_price_isk: null,
    status: "available",
    created_at: "2026-06-24T10:00:00Z",
    images: [img("remoda-shirt5a")],
  }),
  make({
    id: "s6",
    slug: "ledurtoska-svort",
    title: "Svört leðurtaska",
    description: "Tímalaus svört leðurtaska með axlaról.",
    brand: "Mulberry",
    gender: "women",
    category: "bags",
    size: "One size",
    color: "Svartur",
    condition: "excellent",
    price_isk: 34900,
    original_price_isk: 149000,
    status: "available",
    created_at: "2026-06-27T10:00:00Z",
    images: [img("remoda-bag6a"), img("remoda-bag6b")],
  }),
  make({
    id: "s7",
    slug: "herrabuxur-ull",
    title: "Ullarbuxur, dökkgráar",
    description: "Sniðnar ullarbuxur fyrir herra. Lítið notaðar.",
    brand: "Hugo Boss",
    gender: "men",
    category: "pants",
    size: "32",
    color: "Dökkgrár",
    condition: "good",
    price_isk: 7900,
    original_price_isk: 29900,
    status: "sold",
    created_at: "2026-06-18T10:00:00Z",
    images: [img("remoda-pants7a")],
  }),
  make({
    id: "s8",
    slug: "sumarkjoll-blom",
    title: "Blómamynstraður sumarkjóll",
    description: "Léttur sumarkjóll með blómamynstri. Eins og nýr.",
    brand: "& Other Stories",
    gender: "women",
    category: "dresses",
    size: "S",
    color: "Marglitur",
    condition: "excellent",
    price_isk: 6900,
    original_price_isk: 16900,
    status: "available",
    created_at: "2026-06-28T10:00:00Z",
    images: [img("remoda-dress8a"), img("remoda-dress8b")],
  }),
];
